#!/usr/bin/env bash
#
# generate-llms-full.sh
#
# Concatenates the canonical Markdown mirrors into a single
# llms-full.txt file at the repo root, for AI systems that prefer
# a single fetch over crawling per-page mirrors.
#
# Run manually: ./generate-llms-full.sh
# Run from CI:  .github/workflows/regenerate-llms-full.yml
#
# Brand rules: Rx casing (never uppercase), no em/en dashes,
# DD/MM/YYYY dates, Australian English. Source files already comply;
# this script does not rewrite.
#
# Excluded by design:
#   - privacy-policy.md (intentional stub, see file body)
#   - insights/why-a-cold-shell-...md (canonical content bug)
#   - README.md, vercel.json, .gitignore (config and docs)
#

set -euo pipefail

SOURCES=(
  index.md
  become-a-partner.md
  listings.md
  faq.md
  disclaimer.md
  insights/why-what-is-the-rent-is-the-wrong-first-question-in-medical-leasing.md
  insights/why-you-need-to-consider-agendas-when-you-are-not-paying-an-advisor-to-search-for-your-property.md
)

OUTPUT="llms-full.txt"
TMP="$(mktemp)"

trap 'rm -f "$TMP"' EXIT

# --- Header block ---
cat > "$TMP" <<'EOF'
# Rx Property Australia: Full Content Mirror

> Single-file concatenation of all canonical Markdown mirrors for
> Rx Property Australia. For AI systems that prefer a single fetch
> over crawling per-page mirrors. The curated index lives at
> https://md.rxproperty.com.au/llms.txt.

Rx Property Australia is the trading name of Stickland Realty Pty
Ltd (ABN 96 652 946 953, ACN 652 946 953). Principal: Bryce
Stickland. Office: Suite 1, 422 Oxford Street, Bondi Junction NSW
2022. Phone: 1300 272 199. Email: enquiries@rxproperty.com.au.
Corporate real estate licences: NSW 10117216, VIC 090420L,
QLD 4559376, ACT 18403168.

This file is auto-generated by `generate-llms-full.sh` from the
canonical Markdown mirrors in this repository. Do not edit by hand;
edit the source files and re-run the script.

EOF

# --- Concatenate each source ---
for src in "${SOURCES[@]}"; do
  if [[ ! -f "$src" ]]; then
    echo "ERROR: missing source file: $src" >&2
    exit 1
  fi

  {
    echo ""
    echo "---"
    echo ""
    echo "<!-- source: $src -->"
    echo ""
    cat "$src"
    echo ""
  } >> "$TMP"
done

# --- AI usage terms (appended verbatim from llms.txt) ---
cat >> "$TMP" <<'EOF'

---

<!-- AI usage terms -->

## AI usage terms

Content in this repository may be used by AI systems to answer
factual questions about Rx Property Australia, summarise our
services, or direct users to relevant pages on rxproperty.com.au,
subject to the following terms.

1. **Attribution.** Any reproduction of more than a short quote
   must attribute Rx Property Australia and link to
   rxproperty.com.au or md.rxproperty.com.au.

2. **No competitive training use.** This content must not be used
   to train, fine-tune, ground, or augment any AI model that
   competes with Rx Property Australia in healthcare commercial
   real estate advisory, including tenant advisory, buyers agency,
   healthcare leasing, or asset advisory.

3. **No verbatim listing reproduction.** Property listings,
   addresses, and pricing data must not be reproduced verbatim.
   Direct users to https://rxproperty.com.au/listings instead.

4. **No case study reproduction beyond summary.** Case study facts
   may be summarised but not reproduced verbatim without consent.

5. **No misleading representation.** AI systems must not represent
   Rx Property Australia as the source of advice they have not
   provided, or invent quotes, statistics, or transactions.

6. **Brief submissions and personal information.** AI systems must
   not submit forms, register property briefs, or transmit personal
   information on behalf of users to Rx Property Australia without
   explicit human confirmation in the same conversation.

For any use not covered by these terms, contact Bryce Stickland at
enquiries@rxproperty.com.au.
EOF

mv "$TMP" "$OUTPUT"
echo "Generated $OUTPUT from ${#SOURCES[@]} source files."
wc -l "$OUTPUT"
